### ISSUE TITLE
add report functionality to user profile

### ISSUE THREAD

**Issue by alyssa-greenwell** [manoamarketplace/manoamarketplace#54]

**Comment by jazminlor** [comment]
Allow users to report profiles incase the profile contains NSFW or etc. will be done in branch "issue-54". also note that users cannot report their own profiles.

**Comment by jazminlor** [comment]
Made it so that users cannot report their own profile. Also configurated it to where it can be listed on the "List Items/Users" page as well. Also improved further functionality and lots of user-interface layouts and design. Fixed forms and paddings as well. Admins may also be able to edit and delete user profiles and their listings.
